name: Deploy to DockerHub and Remote Server

on:
  push:
    branches:
      - main  # Executa o workflow quando o código é enviado para a branch "main".

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build e Push Imagem para DockerHub
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nome_imagem:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nome_imagem:latest

      - name: Configurar chave SSH para conexão com o servidor remoto
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy no Servidor
        run: |
          ssh -o StrictHostKeyChecking=no aluno@201.23.3.86 << 'EOF'
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nome_imagem:latest
          docker stop nome_do_container || true
          docker rm nome_do_container || true
          docker run -d -p 8084:8084 --name nome_do_container ${{ secrets.DOCKERHUB_USERNAME }}/nome_imagem:latest
          EOF

      - name: Limpeza de chaves SSH temporárias
        run: rm -f ~/.ssh/deploy_key
