name: Deploy to DockerHub and Remote Server

on:
  push:
    branches:
      - main  # Roda o workflow quando o código é enviado para a branch "main".

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build e Push Imagem para DockerHub
        run: |
          docker build -t seu_usuario_dockerhub/nome_imagem:latest .
          docker push seu_usuario_dockerhub/nome_imagem:latest

      - name: Deploy no Servidor
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no aluno@201.23.3.86 << 'EOF'
          docker pull seu_usuario_dockerhub/nome_imagem:latest
          docker stop nome_do_container || true
          docker rm nome_do_container || true
          docker run -d -p 8084:8084 --name nome_do_container seu_usuario_dockerhub/nome_imagem:latest
          EOF

      - name: Limpeza de chaves SSH temporárias
        run: rm ~/.ssh/deploy_key
